version: '3'

services:
  flask:
    container_name: flask_TFG
    image: nooocaaaa/programmingclasses:latest
    restart: unless-stopped
    ports:
      - "35701:35701"
    volumes:
      - ./app:/app
      - ./run.py:/run.py
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://noelia:nocavi12@db:5432/mydatabase
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
      - SECRET_KEY=fe701b7f09e6ef2e015591155de65a8cf85b160e6a75490a
      - UPLOAD_FOLDER=/app/asked_questions
      - STATIC_FOLDER=/app/static
      - CLANG_LIB=/usr/lib/llvm-10/lib
    depends_on:
      - db
    command: bash -c "python run.py"

  db:
    image: nooocaaaa/postgres-tfg:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: noelia
      POSTGRES_PASSWORD: nocavi12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
